version: '3.1'

services:
  wp:
    image: wordpress:latest
    container_name: "${NAME_CONTAINER}_wp"
    ports:
      - ${IP}:${PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db
    links:
      - db
    volumes:
      - WP_VOLUME:/var/www/html


  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${NAME_CONTAINER}_pma"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8081:80
    links:
      - db:db

  db:
    image: mysql:5.7
    container_name: "${NAME_CONTAINER}_db"
    ports:
      - ${IP}:3306:3306
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - DB_VOLUME:/var/lib/mysql

volumes:
  WP_VOLUME:
  DB_VOLUME:
